# Generated by Django 5.0.2 on 2024-03-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Tarea', 'Tarea'), ('Taller', 'Taller'), ('Exposicion', 'Exposicion'), ('TrabajoExperimental', 'Trabajo Experimental')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('recursos', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('enlaces', models.URLField(blank=True)),
                ('fecha_limite', models.DateField()),
                ('hora_limite', models.TimeField()),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('tiempo_restante', models.DurationField(blank=True, editable=False, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_subject', to='subject.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('titulo', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('recursos', models.FileField(upload_to='')),
                ('enlaces', models.URLField(blank=True)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_subject', to='subject.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('fecha_limite', models.DateTimeField()),
                ('tiempo_restante', models.DurationField(blank=True, null=True)),
                ('enlaces', models.URLField(blank=True)),
                ('recursos', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leccion_subject', to='subject.asignatura')),
            ],
        ),
    ]
