# Generated by Django 5.0.2 on 2024-03-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.asignatura'),
        ),
    ]
