# Generated by Django 5.0.2 on 2024-03-04 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_horario_asignatura'),
        ('subject', '0003_remove_asignatura_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='subject.asignatura'),
        ),
    ]
