# Generated by Django 5.0.2 on 2024-03-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_asignatura', models.CharField(choices=[('Practica', 'Practica'), ('Teorica', 'Teorica')], max_length=40)),
                ('modalidad', models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial')], max_length=20)),
                ('url_clases_grabadas', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
