# Generated by Django 5.0.2 on 2024-03-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_horario_asignatura'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='horario',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='schedule.horario'),
        ),
    ]
