# Generated by Django 5.0.2 on 2024-03-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_remove_asignatura_horario_asignatura_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='horarios',
        ),
    ]
